URL_TO_MONITOR_LIST = []  
URL_TO_MONITOR_NAMESPACE = "TestWebsite"
#URL_MONITOR_NAMESPACE = "SameerNewWebHealth"
#URL_MONITOR_NAMESPACE = "SameerWebHealth"
URL_MONITOR_AVAILABILITY = "url_availability"
URL_MONITOR_LATENCY = "url_latency"
THRESHOLDS = [0.28, 0.27, 0.28, 0.29]
